import type { CardCatalog, ChaosCard, CardDefinition, PlayerCard } from "./types";

export const PLAYER_CARDS: PlayerCard[] = [
  {
    id: "restart",
    kind: "contain",
    name: "Restart service",
    glyph: "↻",
    cost: 1,
    text: "+8 stability.",
    rarity: "starter",
    stability: 8,
  },
  {
    id: "diagnose",
    kind: "recover",
    name: "Read the logs",
    glyph: "⌕",
    cost: 1,
    text: "Draw 2.",
    rarity: "starter",
    draw: 2,
  },
  {
    id: "status-page",
    kind: "communicate",
    name: "Status page update",
    glyph: "◉",
    cost: 1,
    text: "−10 harm.",
    rarity: "starter",
    harmReduce: 10,
  },
  {
    id: "throttle",
    kind: "respond",
    name: "Rate-limit traffic",
    glyph: "▤",
    cost: 1,
    text: "Block 10 of the next impact.",
    rarity: "starter",
    shield: 10,
  },
  {
    id: "rollback",
    kind: "contain",
    name: "Roll back to v42",
    glyph: "⟲",
    cost: 2,
    text: "+18 stability. +4 more against a deploy.",
    rarity: "starter",
    stability: 18,
    comboTag: { tag: "deploy", stability: 4 },
  },
  {
    id: "scale-out",
    kind: "contain",
    name: "Scale out",
    glyph: "⇈",
    cost: 2,
    text: "+14 stability.",
    rarity: "starter",
    stability: 14,
  },
  {
    id: "page-oncall",
    kind: "recover",
    name: "Page a second engineer",
    glyph: "✆",
    cost: 1,
    text: "+1 focus next round.",
    rarity: "starter",
    focusNext: 1,
  },
  {
    id: "runbook",
    kind: "recover",
    name: "Open the runbook",
    glyph: "▭",
    cost: 0,
    text: "Draw 1.",
    rarity: "starter",
    draw: 1,
  },
  {
    id: "failover",
    kind: "contain",
    name: "Fail over the region",
    glyph: "⇄",
    cost: 2,
    text: "+22 stability. Negates an infrastructure threat.",
    rarity: "common",
    stability: 22,
    negateTag: "infra",
  },
  {
    id: "all-hands",
    kind: "recover",
    name: "Call all hands",
    glyph: "⚑",
    cost: 2,
    text: "Draw 2. +1 focus next round.",
    rarity: "common",
    draw: 2,
    focusNext: 1,
  },
  {
    id: "exec-air-cover",
    kind: "communicate",
    name: "Exec air cover",
    glyph: "◆",
    cost: 1,
    text: "−18 harm.",
    rarity: "rare",
    harmReduce: 18,
  },
  {
    id: "blameless-retro",
    kind: "recover",
    name: "Blameless retro",
    glyph: "✎",
    cost: 1,
    text: "+6 stability. Draw 1.",
    rarity: "common",
    stability: 6,
    draw: 1,
  },
  {
    id: "chaos-monkey",
    kind: "contain",
    name: "Controlled chaos",
    glyph: "☄",
    cost: 0,
    text: "+12 stability. +8 harm.",
    rarity: "rare",
    stability: 12,
    selfHarm: 8,
  },
  {
    id: "capacity-buffer",
    kind: "contain",
    name: "Add capacity buffer",
    glyph: "▥",
    cost: 2,
    text: "+12 stability. Block 8 of the next impact.",
    rarity: "common",
    stability: 12,
    shield: 8,
  },
  {
    id: "load-shedder",
    kind: "respond",
    name: "Shed non-critical load",
    glyph: "▽",
    cost: 1,
    text: "Block 16 of the next impact.",
    rarity: "common",
    shield: 16,
  },
  {
    id: "deploy-freeze",
    kind: "respond",
    name: "Freeze the pipeline",
    glyph: "❄",
    cost: 1,
    text: "+6 stability. Negates a deploy threat.",
    rarity: "common",
    stability: 6,
    negateTag: "deploy",
  },
  {
    id: "war-room",
    kind: "contain",
    name: "Open the war room",
    glyph: "⌂",
    cost: 2,
    text: "This incident, contain cards give +4 more stability.",
    rarity: "rare",
    warRoom: true,
  },
  {
    id: "on-call-swap",
    kind: "recover",
    name: "Swap the on-call",
    glyph: "⇆",
    cost: 1,
    text: "+10 stability. −6 harm.",
    rarity: "common",
    stability: 10,
    harmReduce: 6,
  },
  {
    id: "trace",
    kind: "recover",
    name: "Distributed trace",
    glyph: "⌁",
    cost: 0,
    text: "Draw 2. +1 focus next round.",
    rarity: "rare",
    draw: 2,
    focusNext: 1,
  },
];

export const CHAOS_CARDS: ChaosCard[] = [
  {
    id: "traffic-surge",
    kind: "chaos",
    name: "Traffic surge",
    glyph: "⇶",
    text: "A flash sale nobody scheduled.",
    tag: "load",
    harm: 14,
    stabilityDamage: 0,
    priority: 5,
  },
  {
    id: "retry-storm",
    kind: "chaos",
    name: "Retry storm",
    glyph: "↺",
    text: "Clients retry in lockstep.",
    tag: "load",
    harm: 10,
    stabilityDamage: 0,
    discard: 1,
    priority: 4,
  },
  {
    id: "cache-stampede",
    kind: "chaos",
    name: "Cache stampede",
    glyph: "⛁",
    text: "The cache thundering-herds itself.",
    tag: "load",
    harm: 12,
    stabilityDamage: 0,
    priority: 4,
  },
  {
    id: "bad-deploy",
    kind: "chaos",
    name: "Bad deploy",
    glyph: "⬇",
    text: "v43 ships anyway.",
    tag: "deploy",
    harm: 6,
    stabilityDamage: 10,
    priority: 6,
  },
  {
    id: "memory-leak",
    kind: "chaos",
    name: "Memory leak",
    glyph: "◌",
    text: "Sessions never return. Bleeds every round.",
    tag: "deploy",
    harm: 4,
    stabilityDamage: 0,
    dot: { harm: 4, stabilityDamage: 0, rounds: 3 },
    priority: 5,
  },
  {
    id: "config-drift",
    kind: "chaos",
    name: "Config drift",
    glyph: "⚙",
    text: "A hotfix quietly changed a default.",
    tag: "deploy",
    harm: 0,
    stabilityDamage: 12,
    priority: 5,
  },
  {
    id: "db-lock",
    kind: "chaos",
    name: "Database lock",
    glyph: "▥",
    text: "A migration holds the lock.",
    tag: "infra",
    harm: 12,
    stabilityDamage: 0,
    priority: 5,
  },
  {
    id: "noisy-neighbor",
    kind: "chaos",
    name: "Noisy neighbor",
    glyph: "≋",
    text: "A batch job eats the cluster.",
    tag: "infra",
    harm: 8,
    stabilityDamage: 0,
    drainFocus: 1,
    priority: 4,
  },
  {
    id: "dns-flap",
    kind: "chaos",
    name: "DNS flap",
    glyph: "◍",
    text: "Resolution bounces between zones.",
    tag: "infra",
    harm: 6,
    stabilityDamage: 6,
    priority: 4,
  },
  {
    id: "pager-storm",
    kind: "chaos",
    name: "Pager storm",
    glyph: "✆",
    text: "Every alert fires at once.",
    tag: "people",
    harm: 4,
    stabilityDamage: 0,
    drainFocus: 1,
    priority: 3,
  },
  {
    id: "alert-fatigue",
    kind: "chaos",
    name: "Alert fatigue",
    glyph: "☍",
    text: "Seven dashboards, no signal.",
    tag: "people",
    harm: 6,
    stabilityDamage: 0,
    drawPenalty: 1,
    priority: 3,
  },
  {
    id: "vendor-outage",
    kind: "chaos",
    name: "Vendor outage",
    glyph: "⚡",
    text: "Payments go dark with no warning.",
    tag: "sudden",
    harm: 12,
    stabilityDamage: 0,
    sudden: true,
    priority: 6,
  },
  {
    id: "sla-clock",
    kind: "chaos",
    name: "SLA clock",
    glyph: "◷",
    text: "The window closes with no warning.",
    tag: "sudden",
    harm: 16,
    stabilityDamage: 0,
    sudden: true,
    priority: 6,
  },
  {
    id: "data-corruption",
    kind: "chaos",
    name: "Data corruption",
    glyph: "✖",
    text: "Rows are being corrupted. No warning.",
    tag: "sudden",
    harm: 20,
    stabilityDamage: 10,
    sudden: true,
    priority: 7,
  },
];

export const CARD_CATALOG: CardCatalog = Object.fromEntries(
  [...PLAYER_CARDS, ...CHAOS_CARDS].map((card) => [card.id, card satisfies CardDefinition]),
);

export function getCard(catalog: CardCatalog, cardId: string): CardDefinition | undefined {
  return catalog[cardId];
}
